# Producer HTTP
producer_port=8080
producer_route=/send_sms

# NATS
nats_url=nats://127.0.0.1:4222
nats_stream_name=SMS
nats_subject_outgoing=sms.outgoing
nats_subject_submit=sms.submit
nats_subject_delivery=sms.delivery
nats_consumer_smpp=smpp_consumer

redis_host=127.0.0.1
redis_port=6379

smpp_host=127.0.0.1
smpp_port=2775

smpp_system_id=test
smpp_password=test
smpp_system_type=SMPP

smpp_workers=4
smpp_window_size=20

tps=100

dlr_callback=http://localhost:9000/dlr

log_dir=logs
